version: "3"

services:

  postgres:
    container_name: postgres-research
    image: postgres:15
    environment:
      POSTGRES_DB: research_database
      POSTGRES_USER: app
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./src/data/:/data/

  mongo:
    container_name: mongo-research
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./src/data/:/data/

  mongo-express:
    container_name: mongo-express-research
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
